add_test( FastFinRL.LoadDataFrame /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.LoadDataFrame]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.LoadDataFrame PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.ResetBasic /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.ResetBasic]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.ResetBasic PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.ResetSeedReproducibility /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.ResetSeedReproducibility]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.ResetSeedReproducibility PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.ResetSeedAutoIncrement /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.ResetSeedAutoIncrement]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.ResetSeedAutoIncrement PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.ResetAutoIncrementReproducibility /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.ResetAutoIncrementReproducibility]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.ResetAutoIncrementReproducibility PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.StepBuy /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.StepBuy]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.StepBuy PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.StepSell /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.StepSell]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.StepSell PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.StopLoss /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.StopLoss]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.StopLoss PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.TerminalCondition /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.TerminalCondition]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.TerminalCondition PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.DoneConditionBankrupt /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.DoneConditionBankrupt]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.DoneConditionBankrupt PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.IndicatorsMatchDataFrame /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.IndicatorsMatchDataFrame]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.IndicatorsMatchDataFrame PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.MultiTicker /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.MultiTicker]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.MultiTicker PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.ContinuousEpisodeTraining /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.ContinuousEpisodeTraining]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.ContinuousEpisodeTraining PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.RewardCalculation /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.RewardCalculation]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.RewardCalculation PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( FastFinRL.InfoDictionary /mnt/c/Users/necro/CLionProjects/fast_finrl/fast_finrl_tests [==[--gtest_filter=FastFinRL.InfoDictionary]==] --gtest_also_run_disabled_tests)
set_tests_properties( FastFinRL.InfoDictionary PROPERTIES WORKING_DIRECTORY /mnt/c/Users/necro/CLionProjects/fast_finrl SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( fast_finrl_tests_TESTS FastFinRL.LoadDataFrame FastFinRL.ResetBasic FastFinRL.ResetSeedReproducibility FastFinRL.ResetSeedAutoIncrement FastFinRL.ResetAutoIncrementReproducibility FastFinRL.StepBuy FastFinRL.StepSell FastFinRL.StopLoss FastFinRL.TerminalCondition FastFinRL.DoneConditionBankrupt FastFinRL.IndicatorsMatchDataFrame FastFinRL.MultiTicker FastFinRL.ContinuousEpisodeTraining FastFinRL.RewardCalculation FastFinRL.InfoDictionary)
